<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Ericka Salas" />
    
    <link rel="shortcut icon" type="image/x-icon" href="../../img/favicon.ico">
    <title>Project 1: Exploratory Data Analysis</title>
    <meta name="generator" content="Hugo 0.79.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">
      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="../../"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="../../post/">BLOG</a></li>
        
        <li><a href="../../projects/">PROJECTS</a></li>
        
        <li><a href="../../resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="../../project/project1/">Project 1: Exploratory Data Analysis</a></strong>
          </h3>
        </div>
 
<div class="blog-title">
          <h4>
         January 1, 0001 
            &nbsp;&nbsp;
            
          </h4>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<div id="data-wrangling-and-data-exploration" class="section level2">
<h2><strong>Data Wrangling and Data Exploration</strong></h2>
<p><strong>Broadway Data Analysis</strong> <em>Project by: Ericka Salas (efs554)</em></p>
</div>
<div id="introduction-of-broadway-data" class="section level2">
<h2><strong>Introduction of Broadway Data</strong></h2>
<p>Before the COVID-19 pandemic hit, I worked at a box office on UT Austin's campus that mainly sold tickets to concerts and broadway performances. I became a huge broadway fan and for the past two years of working in the office, attending broadway musicals has always been fun and exciting. I miss the feeling of the lights dimming at the beginning of a show or intermission conversations on the songs I enjoyed the most. Since I miss watching broadway musicals, I decided to analyze the different successes of different broadway shows from 19.</p>
<p>The data I gathered is from Github's &quot;Tidy Tuesday&quot; which specifically comes from Playbill, an offical broadway magazine and website. This data shows weekly box office grosses of revenue, attendance in different Broadway League theaters, weekly dates, average ticket price, potential gross, preview numbers, number of performances, etc. There is a total of fifteen numberic variable and two categorical variables. I am looking at two different datasets. One is composed of all the weekly grosses for each show while the other is composed of shows that started before 1985. I am mainly curious on what are the most successful broadway shows of all time. Also, I want to analyze if ticket prices have changed since the premiere of each show. Overall, I expect popular broadway shows like <em>Hamilton, Cats, and The Lion King</em> to have the most revenue or performance attendance.</p>
<div id="loading-necessary-libraries" class="section level4">
<h4>Loading necessary libraries</h4>
<pre class="r"><code>library(tidyverse)
library(dplyr)
# importing this library to easily convert a date to a year
# by itself
library(lubridate)</code></pre>
</div>
<div id="reading-in-data-for-weekly-gross-revenue-attendance-previews-etc." class="section level4">
<h4>Reading in data for weekly gross revenue, attendance, previews, etc.</h4>
<pre class="r"><code>grosses &lt;- readr::read_csv(&quot;https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-28/grosses.csv&quot;, 
    guess_max = 40000)</code></pre>
</div>
<div id="reading-in-data-for-before-1985-shows" class="section level4">
<h4>Reading in data for before 1985 shows</h4>
<pre class="r"><code>pre_1985_starts &lt;- readr::read_csv(&quot;https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-28/pre-1985-starts.csv&quot;)</code></pre>
</div>
</div>
<div id="tidying-rearranging-widelong" class="section level2">
<h2><strong>Tidying: Rearranging Wide/Long</strong></h2>
<p>These datasets are already tidy, however, I untidyed it and gathered it back together to demonstrate how the variables were spread out before. First I piped the data set to spread out the theater location variables with values from the week each performance stopped premiering. Subsequently, to tidy it back together, I gathered all the columns that were theater names and placed them in a column called theater along with its weekend final premier date.</p>
<div id="tidying-the-dataset" class="section level4">
<h4>Tidying the dataset</h4>
<pre class="r"><code>grosses &lt;- grosses %&gt;% pivot_wider(names_from = theatre, values_from = week_ending) %&gt;% 
    pivot_longer(cols = &quot;St. James Theatre&quot;:&quot;Helen Hayes Theater&quot;, 
        names_to = &quot;theatre&quot;, values_to = &quot;week_ending&quot;)
head(grosses)</code></pre>
<pre><code>## # A tibble: 6 x 14
##   week_number weekly_gross_ov… show  weekly_gross potential_gross
##         &lt;dbl&gt;            &lt;dbl&gt; &lt;chr&gt;        &lt;dbl&gt;           &lt;dbl&gt;
## 1           1          3915937 42nd…       282368              NA
## 2           1          3915937 42nd…       282368              NA
## 3           1          3915937 42nd…       282368              NA
## 4           1          3915937 42nd…       282368              NA
## 5           1          3915937 42nd…       282368              NA
## 6           1          3915937 42nd…       282368              NA
## # … with 9 more variables: avg_ticket_price &lt;dbl&gt;, top_ticket_price &lt;dbl&gt;,
## #   seats_sold &lt;dbl&gt;, seats_in_theatre &lt;dbl&gt;, pct_capacity &lt;dbl&gt;,
## #   performances &lt;dbl&gt;, previews &lt;dbl&gt;, theatre &lt;chr&gt;, week_ending &lt;date&gt;</code></pre>
</div>
</div>
<div id="joiningmerging" class="section level2">
<h2>Joining/Merging</h2>
<p>I decided to do a left join since the common variable between the datasets is &quot;show&quot;. The majority of the show data is in the grosses variable, which is the main focus of the data. Therefore, the left join omits the unneccessary variables that are present in the &quot;pre_1985_starts&quot; datasets and joins the shows in both. The cases that were dropped were the shows not present in the overall gross dataset. In other words, a few shows that premiered prior to 1985 and were not present in the gross dataset were dropped.</p>
<div id="joiningmerging-the-broadway-data" class="section level4">
<h4>Joining/Merging the Broadway Data</h4>
<pre class="r"><code>broadway &lt;- left_join(grosses, pre_1985_starts, by = &quot;show&quot;)</code></pre>
</div>
</div>
<div id="wrangling" class="section level2">
<h2><strong>Wrangling</strong></h2>
<div id="grouping-the-data-by-show-and-theater-first-then-filtering-by-a-certain-popular-broadway-theater-in-new-york-city" class="section level4">
<h4>Grouping the data by show and theater first then filtering by a certain popular broadway theater in New York City</h4>
<pre class="r"><code># selecting avg_ticket_price, show, theatre, then arranging
# the ticket prices by most expensive ticket price in theatre
highest_price &lt;- broadway %&gt;% group_by(show) %&gt;% filter(theatre == 
    &quot;Majestic Theatre&quot;) %&gt;% select(avg_ticket_price, show) %&gt;% 
    arrange(desc(avg_ticket_price))
head(highest_price)</code></pre>
<pre><code>## # A tibble: 6 x 2
## # Groups:   show [1]
##   avg_ticket_price show                   
##              &lt;dbl&gt; &lt;chr&gt;                  
## 1             512. Springsteen On Broadway
## 2             511. Springsteen On Broadway
## 3             511. Springsteen On Broadway
## 4             510. Springsteen On Broadway
## 5             510. Springsteen On Broadway
## 6             510. Springsteen On Broadway</code></pre>
</div>
<div id="function-to-calculate-the-number-of-weeks-since-start-and-mutating-the-week-of-run-orginial-number-using-select-and-mutate" class="section level4">
<h4>Function to calculate the number of weeks since start and mutating the week of run orginial number using select() and mutate()</h4>
<pre class="r"><code>calculate_weeks_since_start &lt;- function(x) {
    as.integer(pmax(1, difftime(&quot;1985-06-09&quot;, x, units = &quot;weeks&quot;)))
}

broadway &lt;- broadway %&gt;% mutate(week_of_run_originals = calculate_weeks_since_start(start_date) + 
    row_number())</code></pre>
</div>
<div id="counts-the-number-of-shows-that-have-aired-since-it-started-and-gets-the-top" class="section level4">
<h4>Counts the number of shows that have aired since it started and gets the top</h4>
<pre class="r"><code>broadway %&gt;% group_by(show) %&gt;% summarize(count = n()) %&gt;% arrange(desc(count)) %&gt;% 
    head</code></pre>
<pre><code>## # A tibble: 6 x 2
##   show                     count
##   &lt;chr&gt;                    &lt;int&gt;
## 1 The Phantom of the Opera 97266
## 2 Chicago                  70644
## 3 The Lion King            67628
## 4 Les Miserables           60320
## 5 Cats                     50692
## 6 Wicked                   49590</code></pre>
</div>
<div id="calculates-the-mean-number-of-weeks-from-the-start-of-an-original-premiere-date" class="section level4">
<h4>Calculates the mean number of weeks from the start of an original premiere date</h4>
<pre class="r"><code>broadway %&gt;% summarize(mean_original_week = mean(week_of_run_originals, 
    na.rm = T))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   mean_original_week
##                &lt;dbl&gt;
## 1            582717.</code></pre>
</div>
<div id="this-summarizes-the-top-shows-by-year" class="section level4">
<h4>This summarizes the top shows by year</h4>
<pre class="r"><code>top_tickets &lt;- grosses %&gt;% mutate(year = year(week_ending)) %&gt;% 
    filter(year &gt;= 1996, !is.na(top_ticket_price)) %&gt;% group_by(year, 
    show) %&gt;% summarise(avg_ticket_price = mean(avg_ticket_price, 
    na.rm = TRUE), avg_top_ticket_price = mean(top_ticket_price, 
    na.rm = TRUE)) %&gt;% arrange(desc(avg_top_ticket_price))
top_tickets %&gt;% head</code></pre>
<pre><code>## # A tibble: 6 x 4
## # Groups:   year [4]
##    year show                            avg_ticket_price avg_top_ticket_price
##   &lt;dbl&gt; &lt;chr&gt;                                      &lt;dbl&gt;                &lt;dbl&gt;
## 1  2019 Hamilton                                    285.                 857.
## 2  2020 Hamilton                                    256.                 852.
## 3  2018 Hamilton                                    291.                 849 
## 4  2017 Hamilton                                    277.                 829.
## 5  2017 Hello, Dolly!                               188.                 773.
## 6  2019 Dave Chappelle Live on Broadway             212.                 748</code></pre>
</div>
<div id="getting-the-shows-with-the-most-seats" class="section level4">
<h4>Getting the shows with the most seats</h4>
<pre class="r"><code>broadway %&gt;% group_by(show) %&gt;% summarize(mean_show_seats_sold = mean(seats_sold, 
    na.rm = T), sd_show_seats_sold = sd(seats_sold, na.rm = T)) %&gt;% 
    arrange(desc(mean_show_seats_sold)) %&gt;% head</code></pre>
<pre><code>## # A tibble: 6 x 3
##   show                                    mean_show_seats_sold sd_show_seats_so…
##   &lt;chr&gt;                                                  &lt;dbl&gt;             &lt;dbl&gt;
## 1 David Copperfield: Dreams and Nightmar…               20043.             1177.
## 2 Dr. Seuss&#39; How the Grinch Stole Christ…               15376.             5695.
## 3 Wicked                                                14233.             1125.
## 4 Aladdin                                               13543.              668.
## 5 The Lion King                                         13449.             1210.
## 6 Show Boat                                             13210.             1636.</code></pre>
</div>
<div id="getting-the-theatre-that-sold-the-most-seats" class="section level4">
<h4>Getting the theatre that sold the most seats</h4>
<pre class="r"><code>broadway %&gt;% group_by(theatre) %&gt;% summarize(mean_theatre_seats_sold = mean(seats_sold, 
    na.rm = T), sd_theatre_seats_sold = sd(seats_sold, na.rm = T)) %&gt;% 
    head</code></pre>
<pre><code>## # A tibble: 6 x 3
##   theatre                   mean_theatre_seats_sold sd_theatre_seats_sold
##   &lt;chr&gt;                                       &lt;dbl&gt;                 &lt;dbl&gt;
## 1 46th Street Theatre                         7893.                 3186.
## 2 Al Hirschfeld Theatre                       7893.                 3186.
## 3 Ambassador Theatre                          7893.                 3186.
## 4 American Airlines Theatre                   7893.                 3186.
## 5 August Wilson Theatre                       7893.                 3186.
## 6 Belasco Theatre                             7893.                 3186.</code></pre>
</div>
<div id="getting-the-median-max-and-min-average-ticket-price-for-the-show-cats" class="section level4">
<h4>Getting the median, max, and min average ticket price for the show Cats</h4>
</div>
<div id="these-are-three-out-of-the-five-unique-functions-needed-to-be-used-in-summarize" class="section level4">
<h4>These are three out of the five unique functions needed to be used in summarize</h4>
<pre class="r"><code>broadway %&gt;% filter(show == &quot;Cats&quot;) %&gt;% summarize(med_cats_price = median(avg_ticket_price, 
    na.rm = T), min_cats_price = min(avg_ticket_price, na.rm = T), 
    max_cats_price = max(avg_ticket_price, na.rm = T))</code></pre>
<pre><code>## # A tibble: 1 x 3
##   med_cats_price min_cats_price max_cats_price
##            &lt;dbl&gt;          &lt;dbl&gt;          &lt;dbl&gt;
## 1           42.9           35.6           147.</code></pre>
</div>
<div id="summary-of-results" class="section level3">
<h3>Summary of Results</h3>
<p>After summarizing different variables and grouping them by categoricals, the results of the Broadway shows and theatres appeared to be interesting. The Broadway performance with the highest average ticket price of all time in the Majestic Theatre is Springsteen on Broadway with a price of 511.58 US dollars. <em>The Phantom of the Opera</em> appeared to be the show with the most number of performances with a total of 97266 premieres. The mean number of weeks that have passed since a show has premiered is 582716.9, which means that many of the shows in this data are successful and continue to premiere. <em>Hamilton</em> appeared to be the top show for five years straight, from 2016 to 2020. In addition, the Broadway show that had the most attendance and seats sold ever in a single theater was <em>David Copperfield: Dreams and Nightmares</em>, which had a value of 20043 seat sold. On average, all the Broadway League theatre sold approximately 7893 seats per show.</p>
<p>Since <em>Cats</em> is one of the most classic and popular Broadway shows, I decided to retrieve the median, minimum, and max average price of tickets. The median ticket price is $42.89 and the minimum is 35.59. On average, the maximum ticket price of <em>Cats</em> is 147.17, which means that this performance is less costly than other shows such as <em>Hamilton</em>.</p>
</div>
</div>
<div id="visualizing" class="section level2">
<h2><strong>Visualizing</strong></h2>
<div id="correlation-heatmap-of-numeric-variables" class="section level3">
<h3>Correlation HeatMap of Numeric Variables</h3>
<pre class="r"><code># Getting only the numeric values
cormat &lt;- broadway %&gt;% na.omit() %&gt;% select_if(is.numeric) %&gt;% 
    cor(use = &quot;pair&quot;)

# Making the correlation matrix tidy
tidycor &lt;- cormat %&gt;% as.data.frame %&gt;% rownames_to_column(&quot;var1&quot;) %&gt;% 
    pivot_longer(-1, names_to = &quot;var2&quot;, values_to = &quot;correlation&quot;)

# Creating the correlation heatmap
tidycor %&gt;% ggplot(aes(var1, var2, fill = correlation)) + geom_tile() + 
    scale_fill_gradient2(low = &quot;cyan&quot;, mid = &quot;white&quot;, high = &quot;red&quot;) + 
    geom_text(aes(label = round(correlation, 2)), color = &quot;black&quot;, 
        size = 2) + theme(axis.text.x = element_text(angle = 90, 
    hjust = 1)) + coord_fixed() + labs(title = &quot;Correlation HeatMap&quot;)</code></pre>
<p><img src="../../project/Project1_files/figure-html/unnamed-chunk-14-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<div id="plot-number-one---top-ticket-prices-for-the-past-24-years" class="section level3">
<h3>Plot Number One - Top Ticket Prices for the Past 24 years</h3>
<pre class="r"><code># mapping the three variables
broadway %&gt;% ggplot(aes(year, avg_ticket_price, color = theatre)) + 
    geom_line(data = top_tickets, size = 1.5, col = &quot;blue&quot;, stat = &quot;Summary&quot;) + 
    geom_point(data = top_tickets, size = 1.5, col = &quot;white&quot;, 
        stat = &quot;Summary&quot;) + theme_dark() + # fixing the labels here (x, y, title)
scale_x_continuous(&quot;Year&quot;, breaks = seq(1984, 2020, 2)) + scale_y_continuous(&quot;Average ticket Price (USD $)&quot;) + 
    labs(title = &quot;In the past 24 years, the cost of a Broadway tickets doubled.&quot;, 
        subtitle = &quot;Inflation-adjusted average ticket prices (Jan. 2020 dollars)&quot;, 
        caption = paste(&quot;Source: Playbill&quot;, &quot;Points are average ticket price per show&quot;, 
            sep = &quot;\n&quot;), x = &quot;&quot;, y = &quot;&quot;) + # adding a new theme outside the ones incorporated
theme(text = element_text(family = &quot;Bahnschrift&quot;), panel.grid.minor = element_blank())</code></pre>
<p><img src="../../project/Project1_files/figure-html/unnamed-chunk-15-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<div id="plot-number-two---top-ticket-sales-by-price-in-2020" class="section level3">
<h3>Plot Number Two - Top Ticket Sales by Price in 2020</h3>
<pre class="r"><code># subsetting a dataframe to be the top tickets of only 2020
top_2020 &lt;- top_tickets %&gt;% filter(year == 2020)
# mapping three diff variables
top_2020 %&gt;% ggplot(aes(x = show, y = avg_top_ticket_price, color = as.factor(theatre))) + 
    # adding a theme and setting the x, y, and title labs
theme_light() + geom_bar(data = top_2020, size = 1.5, col = &quot;dark blue&quot;, 
    stat = &quot;Summary&quot;) + labs(title = &quot;The Average Top Ticket Prices of the Top Broadway Shows in 2020&quot;, 
    subtitle = &quot;Inflation-adjusted average ticket prices (Jan. 2020 dollars)&quot;, 
    caption = paste(&quot;Source: Playbill&quot;)) + ylab(&quot;Average Top Ticket Price ($)&quot;) + 
    xlab(&quot;Broadway Show&quot;) + theme(axis.text = element_text(size = 6.5), 
    axis.title = element_text(size = 12, face = &quot;bold&quot;)) + theme(axis.text.x = element_text(angle = 90, 
    vjust = 0.5, hjust = 1, face = &quot;bold&quot;))</code></pre>
<p><img src="../../project/Project1_files/figure-html/unnamed-chunk-16-1.png" width="672" style="display: block; margin: auto;" /> The first plot shows that the average ticket price per broadway show has increased in the past 24 years. In 1996, the average price per ticket was less than 50 dollars. The price increased per year, conveying a positive correlation between year and average ticket price. In 2020, the average ticket price increased to above 100 US dollars. There are a few shows that bring the 2020 prices higher since they are in demand such as Hamilton, Dear Evan Hansen, etc.</p>
<p>The second plot shows the top ticket prices of 2020 before the COVID-19 pandemic. Therefore, this data is not a full year, but the 2020 season from December to late March. This is a reason why A Christmas Carol made onto this plot since it was mainly performed during the holiday season. The show with the highest ticket price is Hamilton, which approximately reaches as high as 1,000 USD. Waitress appears to be the second highest with a max of around 600 USD. The rest of the shows appear to be the same due to the uniform distribution of the plot. The majority of shows had a high price that reach up to 400 USD. This plot shows that these broadway performance were the most paid for and had the most purchased tickets with the above price ranges.</p>
</div>
</div>
<div id="dimensionality-reduction" class="section level2">
<h2><strong>Dimensionality Reduction</strong></h2>
<p>The chosen numeric variables</p>
<div id="taking-the-dataset-and-preparing-it" class="section level4">
<h4>Taking the dataset and preparing it</h4>
<pre class="r"><code>pre_1985_starts &lt;- readr::read_csv(&quot;https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-28/pre-1985-starts.csv&quot;)
grosses &lt;- readr::read_csv(&quot;https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-28/grosses.csv&quot;, 
    guess_max = 40000)
broadway &lt;- left_join(grosses, pre_1985_starts, by = &quot;show&quot;)
broadway &lt;- broadway %&gt;% na.omit()</code></pre>
</div>
<div id="creating-correlation-matrix-and-performing-pca" class="section level4">
<h4>Creating correlation matrix and performing PCA</h4>
<pre class="r"><code>broadway1 &lt;- broadway %&gt;% select(-show, -theatre)
nums &lt;- broadway1 %&gt;% select_if(is.numeric) %&gt;% scale
rownames(nums) &lt;- broadway1$show
broad_pca &lt;- princomp(nums)

datScale &lt;- broadway %&gt;% select(is.numeric) %&gt;% scale
eig1 &lt;- broadway %&gt;% select(is.numeric) %&gt;% cor() %&gt;% eigen()
PCAscores &lt;- datScale %*% eig1$vectors</code></pre>
</div>
<div id="choose-pca-numbers-to-keep" class="section level4">
<h4>Choose PCA numbers to keep</h4>
<pre class="r"><code>eigval &lt;- broad_pca$sdev^2  #square to convert SDs to eigenvalues
varprop = round(eigval/sum(eigval), 2)  #proportion of var explained by each PC</code></pre>
</div>
<div id="grab-pc-scores" class="section level4">
<h4>Grab PC Scores</h4>
<pre class="r"><code># using cumulative property of variance
round(cumsum(eigval)/sum(eigval), 2)</code></pre>
<pre><code>##  Comp.1  Comp.2  Comp.3  Comp.4  Comp.5  Comp.6  Comp.7  Comp.8  Comp.9 Comp.10 
##    0.35    0.59    0.76    0.86    0.94    0.97    0.98    0.99    1.00    1.00 
## Comp.11 
##    1.00</code></pre>
<p>Therefore, 2 or 3 PC's are most ideal</p>
</div>
<div id="visualize-and-interpret" class="section level4">
<h4>Visualize and interpret</h4>
<pre class="r"><code>broadway %&gt;% mutate(PC1 = PCAscores[, 1], PC2 = PCAscores[, 2], 
    PC3 = PCAscores[, 3]) %&gt;% ggplot(aes(PC1, PC2, color = theatre)) + 
    geom_point()</code></pre>
<p><img src="../../project/Project1_files/figure-html/unnamed-chunk-21-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Since we want to know what direction the data varies the most, a Principle Component Analysis. First a correlation matrix was created by scaling the data and retrieving only the numeric variables. Three PC numbers were kept after doing a cumulative proportion of variance. Based on the PCA score plot above, the two theatres that are most clearly separate by PC2 are <em>Ford Center for the Performing Arts</em> and <em>Longacre Theater</em>. In additon, <em>Vivian Beaumont Theater</em>, <em>Gerald Scholenfeld Theatre</em>, and <em>Ford Center for Performing Arts</em> are clearly separate by PC1. There are a few outliers in the clusters, but they are mainly from the <em>Hudson Theatre</em>.</p>
</div>
</div>

            
        <hr>         <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div> 
            </div>
          </div>

   <hr>  <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div> 
        </div>
      </div>
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="../../js/docs.min.js"></script>
<script src="../../js/main.js"></script>

<script src="../../js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
